[package]
name = "atilo"
version = "3.0.0-alpha"
authors = ["YadominJinta <i@yadom.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serde = "1.0"
uname = "0.1.1"
